import React from 'react';

const AboutUs = () => {
  return (
    <div className="text-page">
      <h1>Varför matte fysik provet?</h1>
      
      <section>
        <h2></h2>
        <p>Vill du komma in på ett av Sveriges bästa tekniska program men oroar dig för att dina betyg eller högskoleprovspoäng inte räcker? Då är Matte- och Fysikprovet din chans! Genom att skriva provet får du en extra väg in till program på bland annat Chalmers och KTH.</p>
        <p>På vår hemsida hittar du allt du behöver för att lyckas!.</p>
      </section>

     
    </div>
  );
};

export default AboutUs;